version: "3.8"

services:
  app:
    image: api_time_manager
    command: /bin/sh entrypoint1.sh
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postresql://postgres:postgres@db:5432/api_time_manager
      - SECRET_KEY_BASE=nwNQY5DGTXsdOkCM7Vcol8rXBND8ZnuDyV03CsOfeZ0UwJfSjnRaJKF0W2UjARI+
      
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: api_time_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postresql/data

volumes:
  pgdata: